# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1.xci
# IP: The module: 'gtwizard_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1.xci
# IP: The module: 'gtwizard_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_1/gtwizard_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
