set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/sources_1/ip/gtwizard_0/gtwizard_0/gtwizard_0_in_context.xdc rfile:../../../Loopback_test1.srcs/sources_1/ip/gtwizard_0/gtwizard_0/gtwizard_0_in_context.xdc id:1 order:EARLY scoped_inst:GTP_TX_RX/gtwizard_0_support_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/fullModeDAPHNE/Loopback_test1/Loopback_test1.srcs/constrs_1/new/const_DAPHNE.xdc rfile:../../../Loopback_test1.srcs/constrs_1/new/const_DAPHNE.xdc id:2} [current_design]
current_instance GTP_TX_RX/gtwizard_0_support_i
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.334 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10 [get_ports RP_CLK_IN_P]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports  Q0_CLK0_GTREFCLK_PAD_P_IN]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports  Q0_CLK0_GTREFCLK_PAD_N_IN]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7  [get_ports  TXP_OUT ]
set_property src_info {type:XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7  [get_ports  TXN_OUT ]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11  [get_ports  RXP_IN ]
set_property src_info {type:XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11  [get_ports  RXN_IN ]
set_property src_info {type:XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AA4 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB4 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J8 [get_ports GBL_RST]
set_property src_info {type:XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E3 [get_ports SERIAL_DATA]
set_property src_info {type:XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC C4 [get_ports TX_RST_DONE]
set_property src_info {type:XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B5 [get_ports RX_RST_DONE]
set_property src_info {type:XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A5 [get_ports COMMA_DET]
set_property src_info {type:XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B4 [get_ports ALIGNMENT]
set_property src_info {type:XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells gtwizard_0_support_i/inst/gtwizard_0_init_i/gtwizard_0_i/gt0_gtwizard_0_i/gtpe2_i]
